apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deployment
spec:
  cooldownPeriod: 10
  maxReplicaCount: 2
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  triggers:
  - metadata:
      desiredReplicas: "2"
      start: 00 09 * * 1-4
      end: 00 21 * * 1-4
      timezone: Asia/Kolkata
    type: cron
